
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${DB_URL}/nalmart_data1
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    url: jdbc:mysql://localhost/nalmart
    url: jdbc:mysql://localhost/nalmart_data1
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: 'true'

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: root
#    password: rabbitmq
  jackson:
    serialization:
      fail-on-empty-beans: 'false'

# Mail properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: nalmartinc@gmail.com
    password: fcogleqrxrlonqys

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



password-encoder: true