
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: ${DB_URL}/offers
    #    username: ${DB_USERNAME}
    #    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost/cwift_market_data
    username: root
    password: pass